name: Build

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -o steamgrid-proxy main.go

      - uses: softprops/action-gh-release@v1
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: "continuous"
          prerelease: true
          name: "Continuous Build"
          files: |
            steamgrid-proxy

      - uses: actions/upload-artifact@v4
        with:
          name: steamgrid-proxy
          path: |
            steamgrid-proxy
